apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: minhaz71/railway-booking-user-service:latest
        ports:
        - containerPort: 4000
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb:27017/Railway"
        - name: PORT
          value: "4000"
        - name: BCRYPT_SALT_ROUNDS
          value: "10"
---
# app-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app
  ports:
  - port: 4000
    targetPort: 4000
  type: LoadBalancer  # Or NodePort, depending on your requirements