version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Expose your app's port
    environment:
      - TRAIN_API_URL=http://localhost:7000  # Replace with your actual API URL
      
