version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  # Ensure your Dockerfile is in the same directory
    ports:
      - "4000:4000"  # Map host port 4000 to container port 4000
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/Railway  # Use internal MongoDB connection
      - PORT=4000  
      - BCRYPT_SALT_ROUNDS=10  
    depends_on:
      - mongodb  
    volumes:
      - .:/usr/src/app  
    restart: always 

  mongodb:
    image: mongo:latest  
    ports:
      - "27017:27017"  
    volumes:
      - mongo-data:/data/db  

volumes:
  mongo-data:  
