name: Api gateway Service Docker image test, build and push

on:
  push:
    branches:
      - main
    paths:
      - api-Gateway-Service/**
  pull_request:
    branches:
      - main
    paths:
      - api-Gateway-Service/**

jobs:
  # test:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '18'

  #     - name: Install dependencies
  #       working-directory: ./Train-Service
  #       run: npm install

  #     - name: Run unit tests
  #       working-directory: ./Train-Service
  #       run: npm test
  build:
    runs-on: ubuntu-latest
    # needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./Api-Gateway-Service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/railway-booking-api-gateway-service:latest

      - name: Logout from Docker Hub
        run: docker logout
  
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create target directory on the remote server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.MASTER_IP }} "mkdir -p /home/ubuntu/Manifests/Api-Gateway-Service-Deployment/"

      - name: Copy manifest file to Kubernetes master node
        run: scp -o StrictHostKeyChecking=no -r ./Manifests/Api-Gateway-Service-Deployment/* ubuntu@${{ secrets.MASTER_IP }}:/home/ubuntu/Manifests/Api-Gateway-Service-Deployment/

      - name: Deploy to Kubernetes
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.MASTER_IP }} "
            kubectl apply -f /home/ubuntu/Manifests/Api-Gateway-Service-Deployment/api-gateway-deploy.yml
          "

