---
name: K3s deployment using Ansible
on:
  push:
    branches:
      - main
    paths:
      - 'ansible/**'
  pull_request:
    branches:
      - main
    paths:
      - 'ansible/**'

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy SSH Private Key to Public Instance Git-runner
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/MyKeyPair.pem
          chmod 600 ~/.ssh/MyKeyPair.pem

      - name: Run the Ansible playbook
        run: |
          cd ansible && ansible-playbook -i inventory/hosts.ini site.yml
